### ISSUE TITLE
IDs Should Be Derived From ResourceIDs on Arm Api Management template

### ISSUE THREAD

**Issue by konjp** [Azure/arm-ttk#281] opened 2021-01-20 11:31 UTC
When running test on arm template that creates Api Managment instance getting this error:
`IDs Should Be Derived From ResourceIDs (329 ms) Property: "resourceId" must use one of the following expressions for an resourceId property: extensionResourceId,resourceId,subscriptionResourceId,tenantResourceId,if,parameters,reference,variables,subscription,guid`

Template snippet where is happing is bellow:

`{
  "name": "[concat('ApiApp_', parameters('webServiceName')]",
  "type": "backends",
  "apiVersion": "2020-06-01-preview",
  "dependsOn": [
    "[resourceId('Microsoft.ApiManagement/service', variables('apiManagementInstanceName'))]"
  ],
  "properties": {
    "description": "[parameters('webServiceName')]",
    "resourceId": "[concat('https://management.azure.com', resourceId('Microsoft.Web/sites', parameters('webServiceName')))]",
    "url": "[concat('https://', reference(resourceId('Microsoft.Web/sites', parameters('webServiceName')), '2020-09-01').defaultHostName)]",
    "protocol": "http"
  }
}`

This obviously can be correct behavior from `arm-ttk` perspective. If that is case I'm open to suggestions how to construct correctly that `resourceId ` property to remove this error when running against `arm-ttk` .

**Comment by bmoore-msft** [comment] 2021-01-29 20:03
@konjp - thanks for the issue, this is a good one that I don't have a good solution for (at the moment).  The property is incorrectly named by the RP (that should be resourceUri) but that doesn't help anyone now.  

I think the path for this might be to except the property named "resourceId" when it falls under a backend resource but that's a more significant change to the test so we'll have to schedule that work...

**Comment by SuperKoelle** [comment] 2021-02-10 07:10
I have encountered the same problem. It also fails the test:

 [-] DeploymentTemplate Must Not Contain Hardcoded Uri (11 ms)
        Found hardcoded reference to management.azure.com Index:3793

As @konjp mentions it could be working as intended. But I have also not been able to find any other way to set the management url :/

**Comment by bmoore-msft** [comment] 2021-02-19 02:38
@SuperKoelle - can you open a new/different issue for your case?  Though from the sound of it, I think you need to use the environment() function to get the endpoint (would have to see your template to be sure)

**Comment by SuperKoelle** [comment] 2021-02-22 07:29
Correct. It was fixed with the environment() function. 

I still encounter the exact same issue as @konjp though.

**Comment by bmoore-msft** [comment] 2021-03-26 21:05
Related to exempting properties based on the full json path - not just the property name.  Note we'll have to except this as the path+property combined, not separately (Though that seems obvious now that I type it). e.g.  something like

resourceType/properties/resourceId

Which isn't the actual json path, so we'd have to combine with type - current test has examples on how to exclude based on type, but not this targeted.

**Closed** 2021-06-15 22:38 UTC
Labels: bug, enhancement
