### ISSUE TITLE
"apiVersions Should Be Recent" is broken for API management

### ISSUE THREAD

**Issue by ksgopal4** [Azure/arm-ttk#462] opened 2021-07-19 15:44 UTC
I have suddenly started getting this error in our TTK checker.
`apiVersions-Should-Be-Recent.test.ps1 : Api versions must be a fixed date. Microsoft.ApiManagement/service/apis/ is not.
`
There has been no change to the template. It looks like its confusing 'apiVersion' property internal to API management API with the ARM template resource apiVersion . So the property `  "apiRevision": "1",` is being flagged, which I believe is a mistake.

```
{
      "type": "Microsoft.ApiManagement/service/apis",
      "name": "[concat(parameters('ApimServiceName'), '/', variables('ApiName'))]",
      "apiVersion": "2021-01-01-preview",
      "properties": {
        "displayName": "API",
        "description": "API",
        "serviceUrl": "[parameters('ApiUrl')]",
        "path": "api",
        "protocols": [
          "https"
        ],
        "isCurrent": true,
        "apiVersion": "v1.0",
        "apiRevision": "1",
        "apiVersionSetId": "[resourceId('Microsoft.ApiManagement/service/apiVersionSets', parameters('ApimServiceName'), variables('VersionSetName'))]"
      },      
    },
```

**Comment by bmoore-msft** [comment] 2021-07-20 14:43
@ksgopal4 - I'm not able to reproduce this in the latest version on the following:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "functions": [],
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.ApiManagement/service/apis",
            "name": "[concat(parameters('ApimServiceName'), '/', variables('ApiName'))]",
            "apiVersion": "2021-01-01-preview",
            "properties": {
                "displayName": "API",
                "description": "API",
                "serviceUrl": "[parameters('ApiUrl')]",
                "path": "api",
                "protocols": [
                    "https"
                ],
                "isCurrent": true,
                "apiVersion": "v1.0",
                "apiRevision": "1",
                "apiVersionSetId": "[resourceId('Microsoft.ApiManagement/service/apiVersionSets', parameters('ApimServiceName'), variables('VersionSetName'))]"
            }
        }
    ]
}
```

Can you check to see if you have the latest (there have been some changes in the test in the past week... if you do still see it, can you share the entire template?

**Comment by StartAutomating** [comment] 2021-07-26 20:46
This may have been fixed by a recent PR.  Please attempt to reproduce with most recent bits.

**Comment by bmoore-msft** [comment] 2021-07-26 23:54
@ksgopal4 can you try reproducing this with the latest bits?

**Comment by ksgopal4** [comment] 2021-07-27 07:16
Thank you all, using the latest, original error has gone, instead I now have a new error, without any template change
```
Resources-Should-Not-Be-Ambiguous.test.ps1 : At least one parameter must preceed the resource type in: resourceId('Microsoft.ApiManagement/service/subscriptions', parameters('ApimServiceName'), 'master')
```

**Comment by ksgopal4** [comment] 2021-07-27 07:19
> @ksgopal4 - I'm not able to reproduce this in the latest version on the following:
> 
> ```
> {
>     "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
>     "contentVersion": "1.0.0.0",
>     "parameters": {},
>     "functions": [],
>     "variables": {},
>     "resources": [
>         {
>             "type": "Microsoft.ApiManagement/service/apis",
>             "name": "[concat(parameters('ApimServiceName'), '/', variables('ApiName'))]",
>             "apiVersion": "2021-01-01-preview",
>             "properties": {
>                 "displayName": "API",
>                 "description": "API",
>                 "serviceUrl": "[parameters('ApiUrl')]",
>                 "path": "api",
>                 "protocols": [
>                     "https"
>                 ],
>                 "isCurrent": true,
>                 "apiVersion": "v1.0",
>                 "apiRevision": "1",
>                 "apiVersionSetId": "[resourceId('Microsoft.ApiManagement/service/apiVersionSets', parameters('ApimServiceName'), variables('VersionSetName'))]"
>             }
>         }
>     ]
> }
> ```
> 
> Can you check to see if you have the latest (there have been some changes in the test in the past week... if you do still see it, can you share the entire template?

Hi Brian, yes I do have the latest, from here https://aka.ms/arm-ttk-latest

Thanks

**Comment by bmoore-msft** [comment] 2021-07-27 14:44
@ksgopal4 - thanks for confirming, can you open a new issue for the resources should not be ambiguous test?

**Closed by bmoore-msft** 2021-07-27 14:44 UTC
Labels: Needs: triage :mag:
