### ISSUE TITLE
Write-Error on Parsing Inner Templates

### ISSUE THREAD

**Issue by drewkg** [Azure/arm-ttk#495] opened 2021-08-19 05:21 UTC
When parsing a ARM template containing a deployIfNot policy I get the following

Write-Error: C:\Users\drewk\OneDrive\Documents\PowerShell\Modules\Pester\4.1.0\Functions\Describe.ps1:161:25
Line |
 161 |                  $null = & $Fixture
     |                          ~~~~~~~~~~
     | Could not extract inner templates for 'C:\Users\drewk\Source Code\GitHub\drewkg\Azure\ARM\Policy\SecurityCenter'.

This is the output at the end of the tests for each file.

A sample of the issue can be found at - https://raw.githubusercontent.com/drewkg/Azure/main/ARM/Policy/DiagnosticSettings/LogAnalytics/diagnostics-aa-deploy-policy.json

**Comment by drewkg** [comment] 2021-08-19 08:11
Update,

This appears to not be an individual template that is causing the issue, but when there are multiple linked templates within a single folder.  

This repo / folder triggers the issue 

https://github.com/drewkg/Azure/tree/main/ARM/Policy/DiagnosticSettings/LogAnalytics

When running on this folder, every file except the azureDeploy.json and the last file scanned the following extended error can be observed (taken from an Azure DevOps pipeline)

##[error]            $lastFile = $FolderFiles[-1]
            $isFirstFile = $true                        
            foreach ($fileInfo in $FolderFiles) { # We loop over each file in the folder.
                $isLastFile = $fileInfo -eq $lastFile
                $matchingGroups =
                    @(if ($fileInfo.Schema) { # If a given file has a schema,
                        if ($isFirstFile) {   # see if it's the first file.
                            'AllFiles'        # If it is, add it to the group 'AllFiles'.
                            $isFirstFile = $false
                        }
                        
                        foreach ($key in $TestGroup.Keys) { # Then see if the schema matches the name of the testgroup
                            if ("$key".StartsWith("_") -or "$key".StartsWith('.')) { continue }
                            if ($fileInfo.Schema -match $key) {
                                $key # then run that group of tests.
                            }

The first error message logged above was taken when running ARM-TTK locally on my development environment.

**Comment by StartAutomating** [comment] 2021-11-05 18:01
@drewkg I'm not seeing this reproduced on the most recent TTK, with Pester 4.10.1 (we currently do not support Pester 5).

Can you confirm this is still an issue?

**Comment by drewkg** [comment] 2021-11-05 18:41
I can confirm using the download from https://aka.ms/arm-ttk-latest I still get the error 
Write-Error: C:\Users\drewk\OneDrive\Documents\PowerShell\Modules\Pester\4.1.0\Functions\Describe.ps1:161:25                              Line |                                                                                                                                     161 |                  $null = & $Fixture                                                                                                     |                          ~~~~~~~~~~                                                                                                
     | Could not extract inner templates for 'C:\Users\drewk\Source
     | Code\GitHub\drewkg\Azure\ARM\Policy\DiagnosticSettings\LogAnalytics'. 

You can find the templates that give this error at https://github.com/drewkg/Azure/tree/main/ARM/Policy/DiagnosticSettings/LogAnalytics

**Comment by drewkg** [comment] 2021-11-05 18:46
Have tested with Pester 4.10.1 and the same issue

**Comment by bmoore-msft** [comment] 2021-11-12 21:26
Ok, even without Pester we're not extracting the templates correctly with @drewkg's sample.  So we have the repro.

Note this has the double brackets for escaping expressions in the template, so perhaps need to bring back the other PR.

**Comment by drewkg** [comment] 2021-12-04 13:43
@bmoore-msft this issue is not resolved on teh latest release.

**Comment by ReneRebsdorf** [comment] 2022-01-17 16:33
Agreed.
I am pending creating an issue relating to testing where it takes 30-45 minutes for one of our deployments.
The pipeline is throwing this exact error though, so I'll wait and see if the two are related beforehand.

@bmoore-msft can this issue be re-opened?

**Comment by davidjhole** [comment] 2022-01-19 13:44
I'm getting the same error as above thats causing my pipeline to fail

**Comment by bmoore-msft** [comment] 2022-02-03 21:56
re-opening this issue - anyone have a repro we can use?

**Comment by ReneRebsdorf** [comment] 2022-02-03 23:55
Given this PowerShell script:

```PowerShell
$builtARMFilePath = "$TestFolder/azureDeploy.json"
az bicep build --file $mainBicepFilePath --outfile $builtARMFilePath

# Start ARM-TTK Tests
$TestResults = (Test-AzTemplate -TemplatePath $builtARMFilePath)
```

We get this output during a run:
```text
VERBOSE: Unable to find resources.properties.template around index 13626
VERBOSE: Could not resolve resources.properties.template
Write-Error: C:\Users\rener\source\repos\ProActive\padocop\management\tests\tmp\arm-ttk\Test-AzTemplate.ps1:698
Line |
 698 |                  Test-FileList # we just call it directly.
     |                  ~~~~~~~~~~~~~
     | Could not extract inner templates for 'C:\Users\rener\source\repos\fes\management\tests/tmp//azureDeploy.json'.
```

However 5 minutes later, test output is provided although I am not sure if all our bicep files are tested due to the inner template error.

I actually thought it had to do with some sizing or depth issue, but it turns out just having a single module reference is enough to cause the error.
So I made the attached test to reproduce the issue. Removing the module in the main.bicep file removes the problem.

Maybe a test could be added for nested modules for CI testing to the master branch?

[bicep-repro.zip](https://github.com/Azure/arm-ttk/files/7999029/bicep-repro.zip)

**Comment by bmoore-msft** [comment] 2022-02-04 01:10
Ok, @ReneRebsdorf and I debugged this - in his pipeline he's downloading the ttk, extracting and running the test in that folder - so we are recursing and running tests on the testcases folder for the ttk, which will not work well outside of the unit test framework.

Also, we have no output about the file being tested that's failing - so it wasn't obvious what or why the error.  We need to figure out how communicate the filename of the tested file for certain "fatal" errors.  This would have saved everyone lots of time.................................

**Comment by ReneRebsdorf** [comment] 2022-02-04 01:27
@davidjhole & @drewkg : Could you verify whether you are also inadvertently testing files other than the ones you expect?
Note that even by parsing a specific file with -TemplatePath it will still look for folders in the folder where the file specified with -templatePath is.

**Comment by ReneRebsdorf** [comment] 2022-02-04 01:36
@bmoore-msft 

I do think the relevant information is gathered when processing:

![image](https://user-images.githubusercontent.com/44376705/152457648-9fb8eeec-2da5-4c58-8fa3-41c8297a8ed2.png)

Looking at the purple text, it should have been clear to me that file is not expected in my repository.
However it did not occur to me the slightest that when I dictated the path, as a file, to -TemplatePath that it would possibly recurse to find files.

As we talked about, removing this recurse would at this point however be a breaking change.
However, even though writing up a non-breaking way to determine this, and return a message saying "You passed a file, but we still iterate over folders" seems like an odd pattern.

Maybe this is desirable breaking change that can/should be announced and planned? Wouldn't this easily get in the way if you guys go down the route of supporting bicep files without first building them to arm as well?

**Comment by bmoore-msft** [comment] 2022-02-04 16:46
@ReneRebsdorf - I don't think the purple file is the file that's actually throwing the error, I think it's the *next* file in the list...

The red text in the Write-Error says ```azuredeploy.json``` but I'm pretty sure that's not the correct "template" either.

Aside, I *still* cannot repro your issue, I thought I would be able to get it by extracting the TTK in the folder and running from there but that doesn't show the error... So you must have something else/extra in that folder or something in your invocation I'm missing.  Can you zip the entire tmp folder and share (privately)?

**Comment by davidjhole** [comment] 2022-02-04 17:37
@bmoore-msft  @ReneRebsdorf 
Sorry I haven't had a chance to take a look at this today, my issues were when running the azuredevops atm ttk extension (sam cogan one) and scanning the whole repo not an individual file, it always failed on the platform and solutions folders, these files were bicep files that consumed many modules
folder structure
\Bicep\
-->\modules\
-->\Solution modules\
->>\Platform modules\
then in the files we reference the modules with the relative path "module landingZoneVnet '../modules/vnet.module.bicep' ="

![image](https://user-images.githubusercontent.com/44851206/152574142-deb57c2e-3827-4a63-ae08-beed91c29344.png)

I was going to take the arm-tkk and run it locally against the same compiled modules to see if the results were the same but I expect they will be.

**Comment by bmoore-msft** [comment] 2022-02-04 18:32
@davidjhole - I'm not sure what version sam is using - can you try with the latest and see if it looks like #584 ?  (maybe in reverse order ;))

**Comment by JonasCordsen** [comment] 2022-08-18 12:26
Hello @bmoore-msft 
We have now found 3 files where some fail, and others don't
As far as we can see, it fails if the inner template gets too long.
This is based in these three scenarios
[InnerTemplates.zip](https://github.com/Azure/arm-ttk/files/9373765/InnerTemplates.zip)

FullMainFail.json:
Build of full main with long query in alert rule

FullMainNoFail.json:
Build of full main with short query  (Set to abc) in alert rule

SingeresourceNoFail.json:
Build only of the alert rule bicep with long alert query

**Comment by bmoore-msft** [comment] 2022-08-18 16:14
@StartAutomating - near as I can tell there's something in the regex with the braces `{ }` that confuses expansion of the inner templates.  If I remove those from the `query` property on line 431, the expansions succeeds.

**Comment by JonasCordsen** [comment] 2022-08-18 16:51
@bmoore-msft 

I agree that it must be something in that line, the thing is, the last file is a bicep Build only of that one module, with the full query. And that Works fine, for me atleast, do you see the same thing when you try?

**Comment by bmoore-msft** [comment] 2022-08-18 17:43
yes, I see the same behavior - it works fine when it's not nested.  When we look for nested templates I think we look for matching braces - that query string has unmatched braces and we can't figure out where the templates begin/end.  That's my guess.

Thanks for the t-shooting on this, that would have taken a lot longer without multiple repros.....

**Comment by ReneRebsdorf** [comment] 2022-08-18 18:49
> yes, I see the same behavior - it works fine when it's not nested. When we look for nested templates I think we look for matching braces - that query string has unmatched braces and we can't figure out where the templates begin/end. That's my guess.
> 
> Thanks for the t-shooting on this, that would have taken a lot longer without multiple repros.....

As you may recall, we stumbled upon this back in feb when we were doing screensharing, but as we were debugging a different issue, neither of us thought more of it.
Good spot by Jonas and you on the details of the query string.

Why this has unmatched brackets is beyond me - I think our sentinel engineer used the portal and did an export. I'll inquire with him more.

Is this a sensitivity arm-ttk "needs" to have due to functions being in json strings (just like this serialized json query)? I would think the nested templates were still json objects, and thus didn't require string matching to handle brackets? After all the template is completely valid json.

**Comment by bmoore-msft** [comment] 2022-08-18 19:18
> Is this a sensitivity arm-ttk "needs" to have due to functions being in json strings (just like this serialized json query)? I would think the nested templates were still json objects, and thus didn't require string matching to handle brackets? After all the template is completely valid json.

There's probably something we need to do to make things a bit more robust when looking for the template boundaries...  should just be a json object, how we got [the ttk] into the rathole here I'm not sure...

**Comment by StartAutomating** [comment] 2022-12-02 21:02
Closing as improvements to nested templates make this issue obsolete.

**Closed by StartAutomating** 2022-12-02 21:02 UTC
Labels: bug, Needs: author feedback
