### ISSUE TITLE
2022.01.18 - Parameter must be referenced errors - Conditional resources

### ISSUE THREAD

**Issue by stephenpope** [Azure/arm-ttk#568] opened 2022-01-19 11:29 UTC
Lots (lots!) of these unreferenced parameter errors when the params are clearly referenced (or else the bicep would not build)
Every parameter in my nested templates (bicep modules) is now erroring with ..

```
[-] Parameters Must Be Referenced (238 ms) 
        Unreferenced parameter: redisName
        Unreferenced parameter: redisCacheSKU
        Unreferenced parameter: redisCacheFamily
        Unreferenced parameter: redisCacheCapacity
        Unreferenced parameter: redisEnableNonSslPort
        Unreferenced parameter: redisMinimumTlsVersion
        Unreferenced parameter: eventHubNamespaceName
        Unreferenced parameter: eventHubNamespaceSKU
        Unreferenced parameter: eventHubNamespaceCapacity
        Unreferenced parameter: eventHubNamespaceDisableLocalAuth
        Unreferenced parameter: eventHubNamespaceIsAutoInflateEnabled
        Unreferenced parameter: aksClusterDnsPrefix
        .... long list ....
```

I'm not sure if the issue is around variables held within conditional resources .. for example 

```bicep
resource aks 'Microsoft.ContainerService/managedClusters@2021-08-01' = if(createClusterResource) {  
	  properties: {
	      dnsPrefix: aksClusterDnsPrefix
     }
}
```

**Comment by bmoore-msft** [comment] 2022-01-21 22:09
probably something in the nesting... can you attach a full repro or double click on your setup?  Is it just a bicep file that uses a module?

**Comment by ReneRebsdorf** [comment] 2022-02-21 16:10
@bmoore-msft Not OP - but the file I provided in #567 is built in bicep where conditional modules are used (not resources) - they do *not* reproduce.
Thought it might be of interest to this issue.

@stephenpope mentions multiple parameters, such as redisName - I presume not all of these are used as conditionals, so perhaps the problem is not with the conditional, but elsewhere?

The file in #567 reports both unref vars and params - which to my knowledge it has none, so maybe it is worthwhile for the repro steps you asked for?

**Comment by bmoore-msft** [comment] 2022-02-23 20:59
Yeah, I think the file in #567 should suffice - the pattern I think we have is that we're just not handling innerScope nested templates correctly and that's breaking a not-so-small number of tests...

**Comment by bmoore-msft** [comment] 2022-03-11 21:48
The unreferenced issue should be fixed... @stephenpope - please reopen if you're still seeing it...

**Closed by bmoore-msft** 2022-03-11 21:48 UTC
Labels: Needs: author feedback
