### ISSUE TITLE
HideExisting Must Be Correctly Handled does not handle passing the full object

### ISSUE THREAD

**Issue by ginevragaudioso** [Azure/arm-ttk#445] opened 2021-07-06 21:58 UTC
See 
https://github.com/Azure/arm-ttk/issues/150#issuecomment-871544090
for details.

**Comment by m4h3** [comment] 2021-09-30 15:06
this is failing our marketplace template validation. Please consider this ...

**Comment by bmoore-msft** [comment] 2022-02-04 20:59
Checking to see if anyone has a repro for this... the OP in #150 looks like a bug in the template, not the test...

**Comment by bmoore-msft** [comment] 2022-02-15 22:11
Going to close this one out until we can nail down a repro

**Closed by bmoore-msft** 2022-02-15 22:11 UTC
Labels: bug

**Comment by jimdigriz** [comment] 2024-07-17 16:29
For others stumbling on this, the problem is if the arguments are deeper than a single level in the output, so this will *not* work:
```
"outputs": {
  "foo": {
    "bar": {
      "newOrExisting": "[...]"
    }
  }
}
```

This though will:
```
"outputs": {
  "foobar": {
    "newOrExisting": "[...]"
  }
}
```

**Comment by jimdigriz** [comment] 2024-07-17 16:33
Scratch that...still does not work, you have to do something like:
```
"outputs": {
      "ip0v6": {
        "newOrExistingOrNone": "[steps('network').ip0.v6.newOrExistingOrNone]",
        "resourceGroup": "[steps('network').ip0.v6.resourceGroup]",
        "name": "[steps('network').ip0.v6.name]"
      }
}
```
