### ISSUE TITLE
Test-AzTemplate.sh does not recognize newer API versions in reference()

### ISSUE THREAD

**Issue by lanceshelton** [Azure/arm-ttk#576] opened 2022-01-28 16:28 UTC
When running Test-AzTemplate.sh on a template with the following code:
` reference('loadbalancername', '2021-05-01')`

the test complains that the ApiVersion does not exist, and prints an outdated list of versions:

`    [-] apiVersions Should Be Recent In Reference Functions (1887 ms)                                                                                                                                     Microsoft.Network/loadBalancers is using an invalid apiVersion. Index:48310                                                                                                                       ApiVersion not found for:  and version         Valid Api Versions found:                                                                                                                          2020-08-01                                                                                                                                                                                        2020-07-01                                                                                                                                                                                        2020-06-01                                                                                                                                                                                        2020-05-01                                                                                                                                                                                        2020-04-01                                                                                                                                                                                        2020-03-01`

It does not complain about resources created in the template using the newer API versions.  It only complains when a newer version is specified in reference().

**Comment by bmoore-msft** [comment] 2022-02-03 21:49
@lanceshelton - I'm not able to reproduce this on the latest version...  can you check to see you have the latest and if so, attach template we can use to repro?

**Comment by bmoore-msft** [comment] 2022-03-11 21:48
Closing this out since we don't have a repro

**Closed by bmoore-msft** 2022-03-11 21:48 UTC
Labels: Needs: author feedback
